CREATE DATABASE BD_MDO

USE BD_MDO


CREATE TABLE ESTUDIANTES
(
	matriculaEstudiante NVARCHAR(15) NOT NULL PRIMARY KEY,
	nombreEstudiante NVARCHAR(100) NOT NULL,	
	carreraEstudiante NVARCHAR(100) NOT NULL,
	correoEstudiante NVARCHAR(100) NOT NULL,
	telefonoEstudiante NVARCHAR(15),
	fechaEstudiante DATE NOT NULL,
	generoEstudiante NVARCHAR(10) NOT NULL,
	turnoEstudiante NVARCHAR(10) NOT NULl,
	ingresoEstudiante NVARCHAR(50) NOT NULL,
	becaEstudiante BIT NOT NULL DEFAULT 0,
	porcentajebecaEstudiante INT CHECK (porcentajebecaEstudiante BETWEEN 0 AND 100),
	tcEstudiante BIT NOT NULL
)

CREATE TABLE MATERIAS
(
	CODIGOMATERIA NVARCHAR(20) PRIMARY KEY,
	NOMBREMATERIA NVARCHAR(100) NOT NULL,
	CREDITOS INT NOT NULL CHECK (CREDITOS BETWEEN 1 AND 4),
	CARRERA NVARCHAR(100) NOT NULL
)

CREATE TABLE CALIFICACIONES
(
	IDCALIFICACION INT PRIMARY KEY IDENTITY(1,1),
	MATRICULAESTUDIANTE NVARCHAR(15) NOT NULL FOREIGN KEY REFERENCES ESTUDIANTES(matriculaEstudiante),
	CODIGOMATERIA NVARCHAR(20) NOT NULL FOREIGN KEY REFERENCES MATERIAS(CODIGOMATERIA),
	NOTA DECIMAL(5,2) NOT NULL CHECK (NOTA BETWEEN 0 AND 100),
	PERIODO NVARCHAR(20) NOT NULL
)

select * from MATERIAS

